import { teleopTeamAverages, teleopTeamMax, matchTeamAverages, matchTeamMax, autonomousMovedTeamAverages, autonomousSpeakerTeamAverages, autonomousSpeakerTeamMax, autonomousFoulTeamAverages, autonomousFoulTeamMax, autonomousSpeakerAccuracyTeamAverages } from './functions.js';
import scoutingData from '../../scouting_data_dcmp.json'; 

export const averageTeleopScoreConfig = {
    data: teleopTeamAverages(scoutingData),
    title: 'Tele-Op Average Notes By Team',
    scoringTypes: [
        {
            key: 'averageScore',
            label: 'Average Score',
            color: '#70dbed',
        },
    ],
    chartSettings: {
        showGridlines: true,
        gridlineColor: '#444444',
    },
    xKey: 'teamNumber',
    yKey: 'averageScore',
    xAxisLabel: 'Team Number',
    yAxisLabel: 'Average Score',
    yAxisMin: 0,
    yAxisMax: 'auto',
    showTooltip: true,
    tooltipSettings: {
        backgroundColor: '#333333',
        borderRadius: '8px',
        fontSize: '0.875rem',
        cursorColor: 'rgba(255, 255, 255, 0.1)',
    },
    showLegend: true,
    interactiveLegend: true,
    legendPosition: 'top',
    responsive: true,
    maintainAspectRatio: true,
    showDataLabels: false,
    dataLabelPosition: 'inside',
    dataLabelRotation: 0,
};

export const maxTeleopScoreConfig = {
    data: teleopTeamMax(scoutingData),
    title: 'Tele-Op Max Notes By Team',
    scoringTypes: [
        {
            key: 'maxScore',
            label: 'Max Score',
            color: '#f2495c',
        },
    ],
    chartSettings: {
        showGridlines: true,
        gridlineColor: '#444444',
    },
    xKey: 'teamNumber',
    yKey: 'maxScore',
    xAxisLabel: 'Team Number',
    yAxisLabel: 'Max Score',
    yAxisMin: 0,
    yAxisMax: 'auto',
    showTooltip: true,
    tooltipSettings: {
        backgroundColor: '#333333',
        borderRadius: '8px',
        fontSize: '0.875rem',
        cursorColor: 'rgba(255, 255, 255, 0.1)',
    },
    showLegend: true,
    interactiveLegend: true,
    legendPosition: 'top',
    responsive: true,
    maintainAspectRatio: true,
    showDataLabels: false,
    dataLabelPosition: 'inside',
    dataLabelRotation: 0,
};

export const averageMatchScoreConfig = {
    data: matchTeamAverages(scoutingData),
    title: 'Match Average Notes By Team',
    scoringTypes: [
        {
            key: 'averageScore',
            label: 'Average Score',
            color: '#3498db',
        },
    ],
    chartSettings: {
        showGridlines: true,
        gridlineColor: '#444444',
    },
    xKey: 'teamNumber',
    yKey: 'averageScore',
    xAxisLabel: 'Team Number',
    yAxisLabel: 'Average Score',
    yAxisMin: 0,
    yAxisMax: 'auto',
    showTooltip: true,
    tooltipSettings: {
        backgroundColor: '#333333',
        borderRadius: '8px',
        fontSize: '0.875rem',
        cursorColor: 'rgba(255, 255, 255, 0.1)',
    },
    showLegend: true,
    interactiveLegend: true,
    legendPosition: 'top',
    responsive: true,
    maintainAspectRatio: true,
    showDataLabels: false,
    dataLabelPosition: 'inside',
    dataLabelRotation: 0,
};

export const maxMatchScoreConfig = {
    data: matchTeamMax(scoutingData),
    title: 'Match Max Notes By Team',
    scoringTypes: [
        {
            key: 'maxScore',
            label: 'Max Score',
            color: '#e74c3c',
        },
    ],
    chartSettings: {
        showGridlines: true,
        gridlineColor: '#444444',
    },
    xKey: 'teamNumber',
    yKey: 'maxScore',
    xAxisLabel: 'Team Number',
    yAxisLabel: 'Max Score',
    yAxisMin: 0,
    yAxisMax: 'auto',
    showTooltip: true,
    tooltipSettings: {
        backgroundColor: '#333333',
        borderRadius: '8px',
        fontSize: '0.875rem',
        cursorColor: 'rgba(255, 255, 255, 0.1)',
    },
    showLegend: true,
    interactiveLegend: true,
    legendPosition: 'top',
    responsive: true,
    maintainAspectRatio: true,
    showDataLabels: false,
    dataLabelPosition: 'inside',
    dataLabelRotation: 0,
};

export const averageAutonomousScoreConfig = {
    data: autonomousSpeakerTeamAverages(scoutingData),
    title: 'Autonomous Average Notes By Team',
    scoringTypes: [
        {
            key: 'averageScore',
            label: 'Average Score',
            color: '#8ab8ff',
        },
    ],
    chartSettings: {
        showGridlines: true,
        gridlineColor: '#444444',
    },
    xKey: 'teamNumber',
    yKey: 'averageScore',
    xAxisLabel: 'Team Number',
    yAxisLabel: 'Average Score',
    yAxisMin: 0,
    yAxisMax: 'auto',
    showTooltip: true,
    tooltipSettings: {
        backgroundColor: '#333333',
        borderRadius: '8px',
        fontSize: '0.875rem',
        cursorColor: 'rgba(255, 255, 255, 0.1)',
    },
    showLegend: true,
    interactiveLegend: true,
    legendPosition: 'top',
    responsive: true,
    maintainAspectRatio: true,
    showDataLabels: false,
    dataLabelPosition: 'inside',
    dataLabelRotation: 0,
};

export const maxAutonomousScoreConfig = {
    data: autonomousSpeakerTeamMax(scoutingData),
    title: 'Autonomous Max Notes By Team',
    scoringTypes: [
        {
            key: 'maxScore',
            label: 'Max Score',
            color: '#fa6400',
        },
    ],
    chartSettings: {
        showGridlines: true,
        gridlineColor: '#444444',
    },
    xKey: 'teamNumber',
    yKey: 'maxScore',
    xAxisLabel: 'Team Number',
    yAxisLabel: 'Max Score',
    yAxisMin: 0,
    yAxisMax: 'auto',
    showTooltip: true,
    tooltipSettings: {
        backgroundColor: '#333333',
        borderRadius: '8px',
        fontSize: '0.875rem',
        cursorColor: 'rgba(255, 255, 255, 0.1)',
    },
    showLegend: true,
    interactiveLegend: true,
    legendPosition: 'top',
    responsive: true,
    maintainAspectRatio: true,
    showDataLabels: false,
    dataLabelPosition: 'inside',
    dataLabelRotation: 0,
};

export const averageAutonomousMovedConfig = {
    data: autonomousMovedTeamAverages(scoutingData),
    title: 'Autonomous Moved Average Notes By Team',
    scoringTypes: [
        {
            key: 'averageScore',
            label: 'Average Score',
            color: '#fade2a',
        },
    ],
    chartSettings: {
        showGridlines: true,
        gridlineColor: '#444444',
    },
    xKey: 'teamNumber',
    yKey: 'averageScore',
    xAxisLabel: 'Team Number',
    yAxisLabel: 'Average Score',
    yAxisMin: 0,
    yAxisMax: 'auto',
    showTooltip: true,
    tooltipSettings: {
        backgroundColor: '#333333',
        borderRadius: '8px',
        fontSize: '0.875rem',
        cursorColor: 'rgba(255, 255, 255, 0.1)',
    },
    showLegend: true,
    interactiveLegend: true,
    legendPosition: 'top',
    responsive: true,
    maintainAspectRatio: true,
    showDataLabels: false,
    dataLabelPosition: 'inside',
    dataLabelRotation: 0,
};

export const averageAutonomousFoulConfig = {
    data: autonomousFoulTeamAverages(scoutingData),
    title: 'Autonomous Foul Average By Team',
    scoringTypes: [
        {
            key: 'averageScore',
            label: 'Average Score',
            color: '#ff0000',
        },
    ],
    chartSettings: {
        showGridlines: true,
        gridlineColor: '#444444',
    },
    xKey: 'teamNumber',
    yKey: 'averageScore',
    xAxisLabel: 'Team Number',
    yAxisLabel: 'Average Score',
    yAxisMin: 0,
    yAxisMax: 'auto',
    showTooltip: true,
    tooltipSettings: {
        backgroundColor: '#333333',
        borderRadius: '8px',
        fontSize: '0.875rem',
        cursorColor: 'rgba(255, 255, 255, 0.1)',
    },
    showLegend: true,
    interactiveLegend: true,
    legendPosition: 'top',
    responsive: true,
    maintainAspectRatio: true,
    showDataLabels: false,
    dataLabelPosition: 'inside',
    dataLabelRotation: 0,
};

export const maxAutonomousFoulConfig = {
    data: autonomousFoulTeamMax(scoutingData),
    title: 'Autonomous Foul Max By Team',
    scoringTypes: [
        {
            key: 'maxScore',
            label: 'Max Score',
            color: '#ff0000',
        },
    ],
    chartSettings: {
        showGridlines: true,
        gridlineColor: '#444444',
    },
    xKey: 'teamNumber',
    yKey: 'maxScore',
    xAxisLabel: 'Team Number',
    yAxisLabel: 'Max Score',
    yAxisMin: 0,
    yAxisMax: 'auto',
    showTooltip: true,
    tooltipSettings: {
        backgroundColor: '#333333',
        borderRadius: '8px',
        fontSize: '0.875rem',
        cursorColor: 'rgba(255, 255, 255, 0.1)',
    },
    showLegend: true,
    interactiveLegend: true,
    legendPosition: 'top',
    responsive: true,
    maintainAspectRatio: true,
    showDataLabels: false,
    dataLabelPosition: 'inside',
    dataLabelRotation: 0,
};

export const averageAutonomousSpeakerAccuracyConfig = {
    data: autonomousSpeakerAccuracyTeamAverages(scoutingData),
    title: 'Autonomous Speaker Accuracy Average Notes By Team',
    scoringTypes: [
        {
            key: 'averageScore',
            label: 'Average Score',
            color: '#ff0000',
        },
    ],
    chartSettings: {
        showGridlines: true,
        gridlineColor: '#444444',
    },
    xKey: 'teamNumber',
    yKey: 'averageScore',
    xAxisLabel: 'Team Number',
    yAxisLabel: 'Average Score',
    yAxisMin: 0,
    yAxisMax: 'auto',
    showTooltip: true,
    tooltipSettings: {
        backgroundColor: '#333333',
        borderRadius: '8px',
        fontSize: '0.875rem',
        cursorColor: 'rgba(255, 255, 255, 0.1)',
    },
    showLegend: true,
    interactiveLegend: true,
    legendPosition: 'top',
    responsive: true,
    maintainAspectRatio: true,
    showDataLabels: false,
    dataLabelPosition: 'inside',
    dataLabelRotation: 0,
};